version: '2'
services:
    mongo:
        image: mongo:3
        container_name: "mongo-db"
        volumes:
            - ./mongo/data:/db/data
        ports:
            - "27017:27017"
    api:
        build: ./parse-server
        container_name: "parse-server"
        ports:
            - "1337:1337"
        environment:
          PORT: 1337
          DATABASE_URI: mongodb://mongo:27017/dev
          APP_ID: "YOUR PARSE APP ID"
          MASTER_KEY: "YOUR PARSE MASTER KEY"
          PARSE_MOUNT: "/parse"
          SERVER_URL: "YOUR PARSE SERVER URL"
          VIRTUAL_HOST: "YOUR PARSE SERVER URL"
          LETSENCRYPT_HOST: "YOUR PARSE SERVER URL"
          LETSENCRYPT_EMAIL: "YOUR EMAIL"
        volumes:
            - ./parse-server/cloud:/parse/cloud
            - ./parse-server/public:/parse/public
        depends_on:
            - mongo
    dashboard:
        build: ./dashboard
        container_name: "parse-dashboard"
        environment:
            PORT: 4040
            PARSE_DASHBOARD_ALLOW_INSECURE_HTTP: "True"
            PARSE_DASHBOARD_SERVER_URL: "YOUR PARSE SERVER URL"
            PARSE_DASHBOARD_MASTER_KEY: "YOUR PARSE MASTER KEY"
            PARSE_DASHBOARD_APP_ID: "YOUR PARSE APP ID"
            PARSE_DASHBOARD_APP_NAME: "YOUR APP NAME"
            PARSE_DASHBOARD_USER_ID: "YOUR USERNAME"
            PARSE_DASHBOARD_USER_PASSWORD: "YOUR PASSWORD"
            VIRTUAL_HOST: "YOUR PARSE DASHBOARD URL"
            LETSENCRYPT_HOST: "YOUR PARSE DASHBOARD URL"
            LETSENCRYPT_EMAIL: "YOUR EMAIL"
        ports:
            - "4040:4040"
    web-app:
        build: ./web-app
        container_name: "web-app"
        ports:
            - "3000:3000"
        environment:
            VIRTUAL_HOST: "YOUR NEXT APP URL"
            LETSENCRYPT_HOST: "YOUR NEXT APP URL"
            LETSENCRYPT_EMAIL: "YOUR EMAIL"
    nginx-proxy:
        image: jwilder/nginx-proxy
        container_name: nginx-proxy
        ports:
          - '80:80'
          - '443:443'
          volumes:
          - /var/run/docker.sock:/tmp/docker.sock:ro
          - /etc/nginx/vhost.d
          - /usr/share/nginx/html
          - /apps/web/ssl:/etc/nginx/certs:ro
    ssl-companion:
        image: jrcs/letsencrypt-nginx-proxy-companion
        container_name: ssl-companion
        volumes:
          - /apps/web/ssl:/etc/nginx/certs:rw
          - /var/run/docker.sock:/var/run/docker.sock:ro
        volumes_from:
          - nginx-proxy
        depends_on:
          - nginx-proxy
